language: node_js
node_js: '12'
branches:
  only:
  - master
script:
  - npm run dist
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: demo/dist
  verbose: true
  on:
    branch: master
